#  ____  _               _                      _
# | __ )| |_   _  ___   / \   _ __ ___ __ _  __| | ___
# |  _ \| | | | |/ _ \ / _ \ | '__/ __/ _` |/ _` |/ _ \
# | |_) | | |_| |  __// ___ \| | | (_| (_| | (_| |  __/
# |____/|_|\__,_|\___/_/   \_|_|  \___\__,_|\__,_|\___|
#
# [!] Arcade by Blueva | https://blueva.net/store/blue-arcade [!]

# Water Well Module Settings
# Visual representation in menus
menus:
  vote:
    item: "WATER_BUCKET"

# Game items (optional)
items:
  starting_items: []

# Potion effects (optional)
effects:
  starting_effects: []
  respawn_effects: []
